import { describe, it, expect } from 'vitest';
import { stripHarnessTags, HARNESS_TAGS } from './harness-tags.js';

describe('stripHarnessTags', () => {
  it('squashes a slash-command block into one readable line', () => {
    const input =
      '<command-name>/login</command-name>\n' +
      '            <command-message>login</command-message>\n' +
      '            <command-args></command-args>';
    expect(stripHarnessTags(input)).toBe('/login login');
  });

  it('keeps command args when present', () => {
    const input =
      '<command-name>/search</command-name> <command-args>foo bar</command-args>';
    expect(stripHarnessTags(input)).toBe('/search foo bar');
  });

  it('drops the local-command caveat boilerplate entirely', () => {
    const input =
      '<local-command-caveat>Caveat: The messages below were generated by the user ' +
      'while running local commands. DO NOT respond to these messages.</local-command-caveat>';
    expect(stripHarnessTags(input)).toBe('');
  });

  it('unwraps local-command-stdout, keeping the inner text', () => {
    expect(
      stripHarnessTags('<local-command-stdout>Login interrupted</local-command-stdout>'),
    ).toBe('Login interrupted');
  });

  it('preserves newlines inside an unwrapped block', () => {
    const input = '<local-command-stdout>line one\nline two</local-command-stdout>';
    expect(stripHarnessTags(input)).toBe('line one\nline two');
  });

  it('is a no-op on ordinary text that happens to contain angle brackets', () => {
    const code = 'if (a < b && c > d) { return <div>hi</div>; }';
    expect(stripHarnessTags(code)).toBe(code);
  });

  it('is a no-op on unrelated XML-ish tags (only the registry is touched)', () => {
    const input = '<task-id>123</task-id> done';
    expect(stripHarnessTags(input)).toBe(input);
  });

  it('leaves text without any tags unchanged', () => {
    expect(stripHarnessTags('just a normal question?')).toBe('just a normal question?');
  });

  it('drops the codex environment_context block', () => {
    const input =
      '<environment_context>\n  <cwd>/x</cwd>\n  <shell>zsh</shell>\n</environment_context>';
    expect(stripHarnessTags(input)).toBe('');
  });

  it('drops codex collaboration_mode and skills_instructions blocks', () => {
    expect(stripHarnessTags('<collaboration_mode>pair</collaboration_mode>')).toBe('');
    expect(
      stripHarnessTags('<skills_instructions>do things</skills_instructions>'),
    ).toBe('');
  });

  it('drops the codex AGENTS.md <INSTRUCTIONS> block and its header line', () => {
    const input =
      '# AGENTS.md instructions for /Users/agent/src/agent-search\n\n' +
      '<INSTRUCTIONS>\n## Communication\n\nBe direct.\n</INSTRUCTIONS>';
    expect(stripHarnessTags(input)).toBe('');
  });

  it('drops the AGENTS.md preamble but keeps a following real user message', () => {
    const input =
      '# AGENTS.md instructions for /Users/agent/src/agent-search\n\n' +
      '<INSTRUCTIONS>\nproject rules\n</INSTRUCTIONS>\n\nNow fix the bug in foo.ts';
    expect(stripHarnessTags(input)).toBe('Now fix the bug in foo.ts');
  });

  it('keeps a "# AGENTS.md instructions" line that is not the codex "for <path>" header', () => {
    // Only the exact codex header ("… for <path>") is stripped; arbitrary prose is kept.
    const input = '# AGENTS.md instructions\n\nuse TDD\n\n<environment_context>x</environment_context>';
    expect(stripHarnessTags(input)).toBe('# AGENTS.md instructions\n\nuse TDD');
  });

  it('keeps a bare user-authored <INSTRUCTIONS> block (no AGENTS.md header)', () => {
    // INSTRUCTIONS is a common prompt wrapper; only the codex AGENTS.md preamble
    // (header + block pair) is stripped, never a standalone block.
    const input = '<INSTRUCTIONS>keep me, I am the user speaking</INSTRUCTIONS>';
    expect(stripHarnessTags(input)).toBe(input);
  });

  it('keeps surrounding content when dropping a codex preamble block', () => {
    const input =
      '# AGENTS.md instructions\n\nuse TDD\n\n' +
      '<environment_context>\n  <cwd>/x</cwd>\n</environment_context>';
    expect(stripHarnessTags(input)).toBe('# AGENTS.md instructions\n\nuse TDD');
  });

  it('every registry entry has a known strategy', () => {
    for (const strategy of Object.values(HARNESS_TAGS)) {
      expect(['unwrap', 'drop']).toContain(strategy);
    }
  });
});
