import { describe, it, expect } from 'vitest';
import { stripHarnessTags, HARNESS_TAGS } from './harness-tags.js';

describe('stripHarnessTags', () => {
  it('squashes a slash-command block into one readable line', () => {
    const input =
      '<command-name>/login</command-name>\n' +
      '            <command-message>login</command-message>\n' +
      '            <command-args></command-args>';
    expect(stripHarnessTags(input)).toBe('/login login');
  });

  it('keeps command args when present', () => {
    const input =
      '<command-name>/search</command-name> <command-args>foo bar</command-args>';
    expect(stripHarnessTags(input)).toBe('/search foo bar');
  });

  it('drops the local-command caveat boilerplate entirely', () => {
    const input =
      '<local-command-caveat>Caveat: The messages below were generated by the user ' +
      'while running local commands. DO NOT respond to these messages.</local-command-caveat>';
    expect(stripHarnessTags(input)).toBe('');
  });

  it('unwraps local-command-stdout, keeping the inner text', () => {
    expect(
      stripHarnessTags('<local-command-stdout>Login interrupted</local-command-stdout>'),
    ).toBe('Login interrupted');
  });

  it('preserves newlines inside an unwrapped block', () => {
    const input = '<local-command-stdout>line one\nline two</local-command-stdout>';
    expect(stripHarnessTags(input)).toBe('line one\nline two');
  });

  it('is a no-op on ordinary text that happens to contain angle brackets', () => {
    const code = 'if (a < b && c > d) { return <div>hi</div>; }';
    expect(stripHarnessTags(code)).toBe(code);
  });

  it('is a no-op on unrelated XML-ish tags (only the registry is touched)', () => {
    const input = '<task-id>123</task-id> done';
    expect(stripHarnessTags(input)).toBe(input);
  });

  it('leaves text without any tags unchanged', () => {
    expect(stripHarnessTags('just a normal question?')).toBe('just a normal question?');
  });

  it('every registry entry has a known strategy', () => {
    for (const strategy of Object.values(HARNESS_TAGS)) {
      expect(['unwrap', 'drop']).toContain(strategy);
    }
  });
});
